version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - 'bundle:/usr/local/bundle'
      - '.:/synak_challenge'
    ports:
      - 3000:3000
    env_file:
      - docker/.env
#    entrypoint:
#      - docker/entrypoint.sh
    command: rails server -e development -p 3000 -b 0.0.0.0
volumes:
  bundle: null
